// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package injector

import (
	"github.com/lyric-demo/wire-demo/bar"
	"github.com/lyric-demo/wire-demo/foo"
)

// Injectors from injector.go:

func InitBarer() bar.Barer {
	fooer := foo.NewFooer()
	barer := bar.NewBarer(fooer)
	return barer
}
